baseURL = 'https://alexandreroman.fr/'
languageCode = 'en-us'
title = 'Alexandre Roman'
theme = []


[params]
  description = "Personal landing page of Alexandre Roman. Ask me anything about my professional journey."

[params.social]
  github = "https://github.com/alexandreroman"
  linkedin = "https://linkedin.com/in/alexandre-roman"
  x = "https://x.com/Alexandre_Roman"
  bluesky = "https://bsky.app/profile/alexandreroman.fr"
