baseURL = 'https://alexandreroman.fr/'
languageCode = 'en-us'
title = 'Alexandre Roman'
theme = []


[params]
  description = "Personal landing page of Alexandre Roman. Software Engineer specializing in Cloud Native technologies, Java, and modern web development."

[params.social]
  github = "https://github.com/alexandreroman"
  linkedin = "https://linkedin.com/in/alexandre-roman"
  x = "https://x.com/Alexandre_Roman"
  bluesky = "https://bsky.app/profile/alexandreroman.fr"
  cv = "https://docs.google.com/document/d/1zer7a3T31x_8r3G3RI-D4T7Mvsu1XHJLocxLm8iLEfg/edit?usp=sharing"
